#https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: "3.7"
services:
  ase-delivery-discovery-server-service:
    container_name: ase-delivery-discovery-server-service
    #    networks:
    #      - gateway
    image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:discovery-server-service
    restart: on-failure
    expose:
      - "8761"
#    depends_on:
#      - mongo
#    environment:
#      SPRING_DATA_MONGODB_HOST: mongo
    ports:
      - "8761:8761"


  ase-delivery-cas-service:
    container_name: ase-delivery-cas-service
    #    networks:
    #      - gateway
    image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:cas-service
    restart: on-failure
    expose:
      - "9091"
    depends_on:
      - mongo_cas
      - ase-delivery-discovery-server-service
    links:
      - ase-delivery-discovery-server-service
    environment:
      SPRING_DATA_MONGODB_HOST: mongo_cas
      # CORS: http://ec2-3-70-186-30.eu-central-1.compute.amazonaws.com:3000
      CORS: http://3.71.93.212:3000
    ports:
      - "9091:9091"


  ase-delivery-dse-service:
    container_name: ase-delivery-dse-service
    #    networks:
    #      - gateway
    image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:dse-service
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - mongo
      - ase-delivery-cas-service
      - ase-delivery-discovery-server-service
    links:
      - ase-delivery-cas-service
      - ase-delivery-discovery-server-service
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      CORS: http://3.71.93.212:3000
    ports:
      - "8080:8080"

  #second instance for demonstrating scaling 
  # ase-delivery-dse-service-2:
  #   container_name: ase-delivery-dse-service-2
  #   #    networks:
  #   #      - gateway
  #   image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:dse-service
  #   restart: on-failure
  #   expose:
  #     - "8081"
  #   depends_on:
  #     - mongo
  #     - ase-delivery-cas-service
  #     - ase-delivery-discovery-server-service
  #   links:
  #     - ase-delivery-cas-service
  #     - ase-delivery-discovery-server-service
  #   environment:
  #     SPRING_DATA_MONGODB_HOST: mongo
  #     CORS: http://3.70.186.30:3000
  #   ports:
  #     - "8081:8080"


  ase-delivery-gateway-service:
    container_name: ase-delivery-gateway-service
    #    networks:
    #      - gateway
    image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:gateway-service
    restart: on-failure
    expose:
      - "10789"
    depends_on:
  #      - mongo
  #      - ase-delivery-cas-service
      - ase-delivery-discovery-server-service
    links:
      - ase-delivery-discovery-server-service
    environment:
      # CORS: http://ec2-3-70-186-30.eu-central-1.compute.amazonaws.com:3000
      CORS: http://3.71.93.212:3000
    ports:
      - "10789:10789"


  ase-delivery-spa-service:
    container_name: ase-delivery-spa-service
      # args:
        # REACT_APP_API_BASE_URL: http://ase-delivery-gateway-service:10789/api
    #    networks:
    #      - gateway
    # environment:
      # - REACT_APP_API_BASE_URL=http://ase-delivery-gateway-service:10789/api
    image: gitlab.lrz.de:5005/ase-21-22/team-8/ase-delivery:spa-service
    restart: on-failure
    expose:
      - "3000"
    depends_on:
      - ase-delivery-gateway-service
    ports:
      - "3000:3000"
    links:
      - "ase-delivery-gateway-service"
  #    environment:
  #      - BACKEND_URL=http://ase-delivery-gateway-service:10789


  #may still have authentication problem
  mongo_cas:
    container_name: mongo_cas
    image: mongo:latest
    command: [--auth]
    restart: always
    #    networks:
    #      - gateway
    expose:
      - "27018"
    ports:
      - "27018:27017"
    #    volumes:
    #      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseAdmin
      MONGO_INITDB_ROOT_PASSWORD: test


  mongo:
    container_name: mongo
    image: mongo:latest
    command: [--auth]
    restart: always
    #    networks:
    #      - gateway
    # expose:
    #   - "27017"
    #   - "27018"
    ports:
      - "27017:27017"
    #    volumes:
    #      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: aseAdmin
      MONGO_INITDB_ROOT_PASSWORD: test

#volumes:
#  mongodbdata:
##
#networks:
#  default:
#    external:
#      name: mongonet

#networks:
#  gateway:
#    driver: "bridge"
