spring:
  data:
    mongodb:

      host: localhost
      port: 27017
      database: aseDelivery

      username: aseAdmin
      password: test
      authentication-database: admin

      auto-index-creation: true

  application:
    name: delivery-service

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ase.delivery.team.8.2021@gmail.com
    password: togu ytsv clzm mkwl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-circular-references: true

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

webconfig:
  cors: ${CORS:http://localhost:3000}


