spring:
  data:
    mongodb:

      host: mongo_cas
      port: 27017
      database: aseDelivery

      username: aseAdmin
      password: test
      authentication-database: admin

      auto-index-creation: true

  application:
    name: authentication-service

server:
  port: ${PORT:9091}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://ase-delivery-discovery-server-service:8761/eureka}

webconfig:
  cors: ${CORS:http://localhost:3000}
